parameters:
#    cstock_articles.example.class: Cstock\ArticlesBundle\Example

services:
#    cstock_articles.example:
#        class: %cstock_articles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
