# cstock_main_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: CstockMainBundle:Default:index }

cstock_main_homepage:
    pattern:  /
    defaults: { _controller: CstockMainBundle:MainMenu:index }