parameters:
#    cstock_main.example.class: Cstock\MainBundle\Example

services:
#    cstock_main.example:
#        class: %cstock_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
